### ISSUE TITLE
How to handle danger.js changelog entry check for dependabot PRs

### ISSUE THREAD

**Issue by lifeparticle** [lifeparticle/binarytree#431]
https://github.com/dangoslen/dependabot-changelog-helper

**Comment by lifeparticle** [comment]
For now, do the following:

```yml
- name: Danger
    if: github.actor != 'dependabot[bot]'
    run: yarn danger ci
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
``` 

[source](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#fetch-metadata-about-a-pull-request)
